package com.example.examapp.Model;

import android.app.Activity;
import android.content.Context;
import android.content.Intent;
import android.view.View;

import com.example.examapp.R;
import com.example.examapp.helper.DatabaseHelper1;

public class Utils {
    private static int sTheme;
    public final static int THEME_DEFAULT = 0;
    public final static int THEME_DARKBLUE = 1;
    public final static int THEME_TEAL = 2;
    private Context context;

    public Utils(Context context) {
        this.context = context;
    }

    public Utils() {

    }

    public void setColorTheme(View v) {
        switch (v.getId()) {
            case R.id.redBtn:
                Constant.theme = R.style.RedTheme;
                break;
            case R.id.darkBlueBtn:
                Constant.theme = R.style.DarkBlueTheme;
                break;
            case R.id.tealBtn:
                Constant.theme = R.style.tealTheme;
                break;
            default:
                Constant.theme = R.style.Theme_ExamApp;
                break;
        }
    }
    public void insertFiveQuestionToCourseOne(){
//Insert question to course1
        Data_Question questionOnwCourseOne = new Data_Question();
        questionOnwCourseOne.setText("Opening Tag of HTML Tag is called as ________.");
        questionOnwCourseOne.setId_answer(2);
        questionOnwCourseOne.setMark(20);
        questionOnwCourseOne.setId_course(0);
        new DatabaseHelper1(context).insertDataToQuestion(questionOnwCourseOne);
        Data_Question questionTwoCourseOne = new Data_Question();
        questionTwoCourseOne.setText("HTML stands for ________.");
        questionTwoCourseOne.setId_answer(1);
        questionTwoCourseOne.setMark(20);
        questionTwoCourseOne.setId_course(0);
        new DatabaseHelper1(context).insertDataToQuestion(questionTwoCourseOne);
        Data_Question questionThreeCourseOne = new Data_Question();
        questionThreeCourseOne.setText("HTML program is saved using _________ extension.");
        questionThreeCourseOne.setId_answer(2);
        questionThreeCourseOne.setMark(20);
        questionThreeCourseOne.setId_course(0);
        new DatabaseHelper1(context).insertDataToQuestion(questionThreeCourseOne);
        Data_Question questionFourCourseOne = new Data_Question();
        questionFourCourseOne.setText("Which of the following is valid colour code ?");
        questionFourCourseOne.setId_answer(1);
        questionFourCourseOne.setMark(20);
        questionFourCourseOne.setId_course(0);
        new DatabaseHelper1(context).insertDataToQuestion(questionFourCourseOne);
        Data_Question questionFiveCourseOne = new Data_Question();
        questionFiveCourseOne.setText("Caption Tag in HTML ?");
        questionFiveCourseOne.setId_answer(1);
        questionFiveCourseOne.setMark(20);
        questionFiveCourseOne.setId_course(0);
        new DatabaseHelper1(context).insertDataToQuestion(questionFiveCourseOne);
    }
    public void insertFiveQuestionToCourseTwo(){
        //Insert question to course2
        Data_Question questionOnwCourseTwo = new Data_Question();
        questionOnwCourseTwo.setText("Which of the following is a server-side Java Script object?");
        questionOnwCourseTwo.setId_answer(3);
        questionOnwCourseTwo.setMark(20);
        questionOnwCourseTwo.setId_course(1);
        new DatabaseHelper1(context).insertDataToQuestion(questionOnwCourseTwo);
        Data_Question questionTowCourseTwo = new Data_Question();
        questionTowCourseTwo.setText("To insert a JavaScript into an HTML page, which tag is used?");
        questionTowCourseTwo.setId_answer(3);
        questionTowCourseTwo.setMark(20);
        questionTowCourseTwo.setId_course(1);
        new DatabaseHelper1(context).insertDataToQuestion(questionTowCourseTwo);
        Data_Question questionThreeCourseTwo = new Data_Question();
        questionThreeCourseTwo.setText("Which of the below is used in Java script to insert special characters?");
        questionThreeCourseTwo.setId_answer(2);
        questionThreeCourseTwo.setMark(20);
        questionThreeCourseTwo.setId_course(1);
        new DatabaseHelper1(context).insertDataToQuestion(questionThreeCourseTwo);
        Data_Question questionFourCourseTwo = new Data_Question();
        questionFourCourseTwo.setText("Which is the correct way to write a JavaScript array?");
        questionFourCourseTwo.setId_answer(3);
        questionFourCourseTwo.setMark(20);
        questionFourCourseTwo.setId_course(1);
        new DatabaseHelper1(context).insertDataToQuestion(questionFourCourseTwo);
        Data_Question questionFiveCourseTwo = new Data_Question();
        questionFiveCourseTwo.setText("Which of the following is correct to write “Hello World” on the web page?");
        questionFiveCourseTwo.setId_answer(2);
        questionFiveCourseTwo.setMark(20);
        questionFiveCourseTwo.setId_course(1);
        new DatabaseHelper1(context).insertDataToQuestion(questionFiveCourseTwo);
    }
    public void insertFiveQuestionToCourseThree(){
        //Insert question to course3
        Data_Question questionOnwCourseThree = new Data_Question();
        questionOnwCourseThree.setText("How can you created rounded corners using CSS3?");
        questionOnwCourseThree.setId_answer(3);
        questionOnwCourseThree.setMark(20);
        questionOnwCourseThree.setId_course(2);
        new DatabaseHelper1(context).insertDataToQuestion(questionOnwCourseThree);
        Data_Question questionTowCourseThree = new Data_Question();
        questionTowCourseThree.setText("How do you add shadow to elements in CSS3?");
        questionTowCourseThree.setId_answer(1);
        questionTowCourseThree.setMark(20);
        questionTowCourseThree.setId_course(2);
        new DatabaseHelper1(context).insertDataToQuestion(questionTowCourseThree);
        Data_Question questionThreeCourseThree = new Data_Question();
        questionThreeCourseThree.setText("How to resize a background image using CSS3?");
        questionThreeCourseThree.setId_answer(1);
        questionThreeCourseThree.setMark(20);
        questionThreeCourseThree.setId_course(2);
        new DatabaseHelper1(context).insertDataToQuestion(questionThreeCourseThree);
        Data_Question questionFourCourseThree = new Data_Question();
        questionFourCourseThree.setText("How to add text shadow using CSS3?");
        questionFourCourseThree.setId_answer(3);
        questionFourCourseThree.setMark(20);
        questionFourCourseThree.setId_course(2);
        new DatabaseHelper1(context).insertDataToQuestion(questionFourCourseThree);
        Data_Question questionFiveCourseThree = new Data_Question();
        questionFiveCourseThree.setText("How to rotate objects using CSS3?");
        questionFiveCourseThree.setId_answer(2);
        questionFiveCourseThree.setMark(20);
        questionFiveCourseThree.setId_course(2);
        new DatabaseHelper1(context).insertDataToQuestion(questionFiveCourseThree);
    }
    public void insertFiveQuestionToCourseFour(){
        //Insert question to course4
        Data_Question questionOnwCourseFour = new Data_Question();
        questionOnwCourseFour.setText("Which of the following ways below are the correct way to get the current date?");
        questionOnwCourseFour.setId_answer(4);
        questionOnwCourseFour.setMark(20);
        questionOnwCourseFour.setId_course(3);
        new DatabaseHelper1(context).insertDataToQuestion(questionOnwCourseFour);
        Data_Question questionTowCourseFour = new Data_Question();
        questionTowCourseFour.setText("USE keyword is used to select a ___________");
        questionTowCourseFour.setId_answer(1);
        questionTowCourseFour.setMark(20);
        questionTowCourseFour.setId_course(3);
        new DatabaseHelper1(context).insertDataToQuestion(questionTowCourseFour);
        Data_Question questionThreeCourseFour = new Data_Question();
        questionThreeCourseFour.setText("What SQL clause is used to restrict the rows returned by a query?");
        questionThreeCourseFour.setId_answer(2);
        questionThreeCourseFour.setMark(20);
        questionThreeCourseFour.setId_course(3);
        new DatabaseHelper1(context).insertDataToQuestion(questionThreeCourseFour);
        Data_Question questionFourCourseFour = new Data_Question();
        questionFourCourseFour.setText("How much character are allowed to create database name?");
        questionFourCourseFour.setId_answer(4);
        questionFourCourseFour.setMark(20);
        questionFourCourseFour.setId_course(3);
        new DatabaseHelper1(context).insertDataToQuestion(questionFourCourseFour);
        Data_Question questionFiveCourseFour = new Data_Question();
        questionFiveCourseFour.setText("Write a select query to retrieve the records from the table “students”?");
        questionFiveCourseFour.setId_answer(1);
        questionFiveCourseFour.setMark(20);
        questionFiveCourseFour.setId_course(3);
        new DatabaseHelper1(context).insertDataToQuestion(questionFiveCourseFour);
    }
    public void insertAnswersToQuestionsForCourseOne(){
        int questionIdOne = 1;
        Data_Answer AnswerOneToQuestionOneForCourseOne = new Data_Answer();
        Data_Answer AnswerTwoToQuestionOneForCourseOne = new Data_Answer();
        Data_Answer AnswerThreeToQuestionOneForCourseOne = new Data_Answer();
        Data_Answer AnswerFourToQuestionOneForCourseOne = new Data_Answer();
        AnswerOneToQuestionOneForCourseOne.setText("Closed Tag");
        AnswerTwoToQuestionOneForCourseOne.setText("Starting Tag");
        AnswerThreeToQuestionOneForCourseOne.setText("Forward Tag");
        AnswerFourToQuestionOneForCourseOne.setText("Enging Tag");
        AnswerOneToQuestionOneForCourseOne.setStatus(0);
        AnswerTwoToQuestionOneForCourseOne.setStatus(1);
        AnswerThreeToQuestionOneForCourseOne.setStatus(0);
        AnswerFourToQuestionOneForCourseOne.setStatus(0);
        AnswerOneToQuestionOneForCourseOne.setId_question(questionIdOne);
        AnswerTwoToQuestionOneForCourseOne.setId_question(questionIdOne);
        AnswerThreeToQuestionOneForCourseOne.setId_question(questionIdOne);
        AnswerFourToQuestionOneForCourseOne.setId_question(questionIdOne);
        new DatabaseHelper1(context).insertDataToAnswer(AnswerOneToQuestionOneForCourseOne);
        new DatabaseHelper1(context).insertDataToAnswer(AnswerTwoToQuestionOneForCourseOne);
        new DatabaseHelper1(context).insertDataToAnswer(AnswerThreeToQuestionOneForCourseOne);
        new DatabaseHelper1(context).insertDataToAnswer(AnswerFourToQuestionOneForCourseOne);
        int questionIdTwo = 2;
        Data_Answer AnswerOneToQuestionTwoForCourseOne = new Data_Answer();
        Data_Answer AnswerTwoToQuestionTwoForCourseOne = new Data_Answer();
        Data_Answer AnswerThreeToQuestionTwoForCourseOne = new Data_Answer();
        Data_Answer AnswerFourToQuestionTwoForCourseOne = new Data_Answer();
        AnswerOneToQuestionTwoForCourseOne.setText("Hyper Text Markup Language");
        AnswerTwoToQuestionTwoForCourseOne.setText("Hyper Text Makeup Language");
        AnswerThreeToQuestionTwoForCourseOne.setText("None of these");
        AnswerFourToQuestionTwoForCourseOne.setText("Hyper Tech Markup Language");
        AnswerOneToQuestionTwoForCourseOne.setStatus(1);
        AnswerTwoToQuestionTwoForCourseOne.setStatus(0);
        AnswerThreeToQuestionTwoForCourseOne.setStatus(0);
        AnswerFourToQuestionTwoForCourseOne.setStatus(0);
        AnswerOneToQuestionTwoForCourseOne.setId_question(questionIdTwo);
        AnswerTwoToQuestionTwoForCourseOne.setId_question(questionIdTwo);
        AnswerThreeToQuestionTwoForCourseOne.setId_question(questionIdTwo);
        AnswerFourToQuestionTwoForCourseOne.setId_question(questionIdTwo);
        new DatabaseHelper1(context).insertDataToAnswer(AnswerOneToQuestionTwoForCourseOne);
        new DatabaseHelper1(context).insertDataToAnswer(AnswerTwoToQuestionTwoForCourseOne);
        new DatabaseHelper1(context).insertDataToAnswer(AnswerThreeToQuestionTwoForCourseOne);
        new DatabaseHelper1(context).insertDataToAnswer(AnswerFourToQuestionTwoForCourseOne);
        int questionIdThree = 3;
        Data_Answer AnswerOneToQuestionThreeForCourseOne = new Data_Answer();
        Data_Answer AnswerTwoToQuestionThreeForCourseOne = new Data_Answer();
        Data_Answer AnswerThreeToQuestionThreeForCourseOne = new Data_Answer();
        Data_Answer AnswerFourToQuestionThreeForCourseOne = new Data_Answer();
        AnswerOneToQuestionThreeForCourseOne.setText(".htl");
        AnswerTwoToQuestionThreeForCourseOne.setText(".html");
        AnswerThreeToQuestionThreeForCourseOne.setText(".hml");
        AnswerFourToQuestionThreeForCourseOne.setText(".htlm");
        AnswerOneToQuestionThreeForCourseOne.setStatus(0);
        AnswerTwoToQuestionThreeForCourseOne.setStatus(1);
        AnswerThreeToQuestionThreeForCourseOne.setStatus(0);
        AnswerFourToQuestionThreeForCourseOne.setStatus(0);
        AnswerOneToQuestionThreeForCourseOne.setId_question(questionIdThree);
        AnswerTwoToQuestionThreeForCourseOne.setId_question(questionIdThree);
        AnswerThreeToQuestionThreeForCourseOne.setId_question(questionIdThree);
        AnswerFourToQuestionThreeForCourseOne.setId_question(questionIdThree);
        new DatabaseHelper1(context).insertDataToAnswer(AnswerOneToQuestionThreeForCourseOne);
        new DatabaseHelper1(context).insertDataToAnswer(AnswerTwoToQuestionThreeForCourseOne);
        new DatabaseHelper1(context).insertDataToAnswer(AnswerThreeToQuestionThreeForCourseOne);
        new DatabaseHelper1(context).insertDataToAnswer(AnswerFourToQuestionThreeForCourseOne);
        int questionIdFour = 4;
        Data_Answer AnswerOneToQuestionFourForCourseOne = new Data_Answer();
        Data_Answer AnswerTwoToQuestionFourForCourseOne = new Data_Answer();
        Data_Answer AnswerThreeToQuestionFourForCourseOne = new Data_Answer();
        Data_Answer AnswerFourToQuestionFourForCourseOne = new Data_Answer();
        AnswerOneToQuestionFourForCourseOne.setText("#000000;");
        AnswerTwoToQuestionFourForCourseOne.setText("#0000000;");
        AnswerThreeToQuestionFourForCourseOne.setText("#00000000;");
        AnswerFourToQuestionFourForCourseOne.setText("#000000000;");
        AnswerOneToQuestionFourForCourseOne.setStatus(1);
        AnswerTwoToQuestionFourForCourseOne.setStatus(0);
        AnswerThreeToQuestionFourForCourseOne.setStatus(0);
        AnswerFourToQuestionFourForCourseOne.setStatus(0);
        AnswerOneToQuestionFourForCourseOne.setId_question(questionIdFour);
        AnswerTwoToQuestionFourForCourseOne.setId_question(questionIdFour);
        AnswerThreeToQuestionFourForCourseOne.setId_question(questionIdFour);
        AnswerFourToQuestionFourForCourseOne.setId_question(questionIdFour);
        new DatabaseHelper1(context).insertDataToAnswer(AnswerOneToQuestionFourForCourseOne);
        new DatabaseHelper1(context).insertDataToAnswer(AnswerTwoToQuestionFourForCourseOne);
        new DatabaseHelper1(context).insertDataToAnswer(AnswerThreeToQuestionFourForCourseOne);
        new DatabaseHelper1(context).insertDataToAnswer(AnswerFourToQuestionFourForCourseOne);
        int questionIdFive = 5;
        Data_Answer AnswerOneToQuestionFiveForCourseOne = new Data_Answer();
        Data_Answer AnswerTwoToQuestionFiveForCourseOne = new Data_Answer();
        Data_Answer AnswerThreeToQuestionFiveForCourseOne = new Data_Answer();
        Data_Answer AnswerFourToQuestionFiveForCourseOne = new Data_Answer();
        AnswerOneToQuestionFiveForCourseOne.setText("Is used to display the Title for table at the top");
        AnswerTwoToQuestionFiveForCourseOne.setText("Is used to display the Title for table at the bottom");
        AnswerThreeToQuestionFiveForCourseOne.setText("Both");
        AnswerFourToQuestionFiveForCourseOne.setText("None");
        AnswerOneToQuestionFiveForCourseOne.setStatus(1);
        AnswerTwoToQuestionFiveForCourseOne.setStatus(0);
        AnswerThreeToQuestionFiveForCourseOne.setStatus(0);
        AnswerFourToQuestionFiveForCourseOne.setStatus(0);
        AnswerOneToQuestionFiveForCourseOne.setId_question(questionIdFive);
        AnswerTwoToQuestionFiveForCourseOne.setId_question(questionIdFive);
        AnswerThreeToQuestionFiveForCourseOne.setId_question(questionIdFive);
        AnswerFourToQuestionFiveForCourseOne.setId_question(questionIdFive);
        new DatabaseHelper1(context).insertDataToAnswer(AnswerOneToQuestionFiveForCourseOne);
        new DatabaseHelper1(context).insertDataToAnswer(AnswerTwoToQuestionFiveForCourseOne);
        new DatabaseHelper1(context).insertDataToAnswer(AnswerThreeToQuestionFiveForCourseOne);
        new DatabaseHelper1(context).insertDataToAnswer(AnswerFourToQuestionFiveForCourseOne);
    }
    public void insertAnswersToQuestionsForCourseTwo(){
        int questionIdOne = 6;
        Data_Answer AnswerOneToQuestionOneForCourseTwo = new Data_Answer();
        Data_Answer AnswerTwoToQuestionOneForCourseTwo = new Data_Answer();
        Data_Answer AnswerThreeToQuestionOneForCourseTwo = new Data_Answer();
        Data_Answer AnswerFourToQuestionOneForCourseTwo = new Data_Answer();
        AnswerOneToQuestionOneForCourseTwo.setText("Function");
        AnswerTwoToQuestionOneForCourseTwo.setText("File");
        AnswerThreeToQuestionOneForCourseTwo.setText("FileUpload");
        AnswerFourToQuestionOneForCourseTwo.setText("Date");
        AnswerOneToQuestionOneForCourseTwo.setStatus(0);
        AnswerTwoToQuestionOneForCourseTwo.setStatus(0);
        AnswerThreeToQuestionOneForCourseTwo.setStatus(1);
        AnswerFourToQuestionOneForCourseTwo.setStatus(0);
        AnswerOneToQuestionOneForCourseTwo.setId_question(questionIdOne);
        AnswerTwoToQuestionOneForCourseTwo.setId_question(questionIdOne);
        AnswerThreeToQuestionOneForCourseTwo.setId_question(questionIdOne);
        AnswerFourToQuestionOneForCourseTwo.setId_question(questionIdOne);
        new DatabaseHelper1(context).insertDataToAnswer(AnswerOneToQuestionOneForCourseTwo);
        new DatabaseHelper1(context).insertDataToAnswer(AnswerTwoToQuestionOneForCourseTwo);
        new DatabaseHelper1(context).insertDataToAnswer(AnswerThreeToQuestionOneForCourseTwo);
        new DatabaseHelper1(context).insertDataToAnswer(AnswerFourToQuestionOneForCourseTwo);
        int questionIdTwo = 7;
        Data_Answer AnswerOneToQuestionTwoForCourseTwo = new Data_Answer();
        Data_Answer AnswerTwoToQuestionTwoForCourseTwo = new Data_Answer();
        Data_Answer AnswerThreeToQuestionTwoForCourseTwo = new Data_Answer();
        Data_Answer AnswerFourToQuestionTwoForCourseTwo = new Data_Answer();
        AnswerOneToQuestionTwoForCourseTwo.setText("<script=’java’>");
        AnswerTwoToQuestionTwoForCourseTwo.setText("<javascript>");
        AnswerThreeToQuestionTwoForCourseTwo.setText("<script>");
        AnswerFourToQuestionTwoForCourseTwo.setText("<js>");
        AnswerOneToQuestionTwoForCourseTwo.setStatus(0);
        AnswerTwoToQuestionTwoForCourseTwo.setStatus(1);
        AnswerThreeToQuestionTwoForCourseTwo.setStatus(0);
        AnswerFourToQuestionTwoForCourseTwo.setStatus(0);
        AnswerOneToQuestionTwoForCourseTwo.setId_question(questionIdTwo);
        AnswerTwoToQuestionTwoForCourseTwo.setId_question(questionIdTwo);
        AnswerThreeToQuestionTwoForCourseTwo.setId_question(questionIdTwo);
        AnswerFourToQuestionTwoForCourseTwo.setId_question(questionIdTwo);
        new DatabaseHelper1(context).insertDataToAnswer(AnswerOneToQuestionTwoForCourseTwo);
        new DatabaseHelper1(context).insertDataToAnswer(AnswerTwoToQuestionTwoForCourseTwo);
        new DatabaseHelper1(context).insertDataToAnswer(AnswerThreeToQuestionTwoForCourseTwo);
        new DatabaseHelper1(context).insertDataToAnswer(AnswerFourToQuestionTwoForCourseTwo);
        int questionIdThree = 8;
        Data_Answer AnswerOneToQuestionThreeForCourseTwo = new Data_Answer();
        Data_Answer AnswerTwoToQuestionThreeForCourseTwo = new Data_Answer();
        Data_Answer AnswerThreeToQuestionThreeForCourseTwo = new Data_Answer();
        Data_Answer AnswerFourToQuestionThreeForCourseTwo = new Data_Answer();
        AnswerOneToQuestionThreeForCourseTwo.setText("&");
        AnswerTwoToQuestionThreeForCourseTwo.setText("\\");
        AnswerThreeToQuestionThreeForCourseTwo.setText("-");
        AnswerFourToQuestionThreeForCourseTwo.setText("%");
        AnswerOneToQuestionThreeForCourseTwo.setStatus(0);
        AnswerTwoToQuestionThreeForCourseTwo.setStatus(0);
        AnswerThreeToQuestionThreeForCourseTwo.setStatus(0);
        AnswerFourToQuestionThreeForCourseTwo.setStatus(1);
        AnswerOneToQuestionThreeForCourseTwo.setId_question(questionIdThree);
        AnswerTwoToQuestionThreeForCourseTwo.setId_question(questionIdThree);
        AnswerThreeToQuestionThreeForCourseTwo.setId_question(questionIdThree);
        AnswerFourToQuestionThreeForCourseTwo.setId_question(questionIdThree);
        new DatabaseHelper1(context).insertDataToAnswer(AnswerOneToQuestionThreeForCourseTwo);
        new DatabaseHelper1(context).insertDataToAnswer(AnswerTwoToQuestionThreeForCourseTwo);
        new DatabaseHelper1(context).insertDataToAnswer(AnswerThreeToQuestionThreeForCourseTwo);
        new DatabaseHelper1(context).insertDataToAnswer(AnswerFourToQuestionThreeForCourseTwo);
        int questionIdFour = 9;
        Data_Answer AnswerOneToQuestionFourForCourseTwo = new Data_Answer();
        Data_Answer AnswerTwoToQuestionFourForCourseTwo = new Data_Answer();
        Data_Answer AnswerThreeToQuestionFourForCourseTwo = new Data_Answer();
        Data_Answer AnswerFourToQuestionFourForCourseTwo = new Data_Answer();
        AnswerOneToQuestionFourForCourseTwo.setText("var txt = new Array(1:\"arr\",2:\"kim\",3:\"jim\")");
        AnswerTwoToQuestionFourForCourseTwo.setText("var txt = new Array:1=(\" arr \")2=(\"kim\")3=(\"jim\")");
        AnswerThreeToQuestionFourForCourseTwo.setText("var txt = new Array(\"arr \",\"kim\",\"jim\")");
        AnswerFourToQuestionFourForCourseTwo.setText("var txt = new Array=\" arr \",\"kim\",\"jim\"");
        AnswerOneToQuestionFourForCourseTwo.setStatus(0);
        AnswerTwoToQuestionFourForCourseTwo.setStatus(0);
        AnswerThreeToQuestionFourForCourseTwo.setStatus(1);
        AnswerFourToQuestionFourForCourseTwo.setStatus(0);
        AnswerOneToQuestionFourForCourseTwo.setId_question(questionIdFour);
        AnswerTwoToQuestionFourForCourseTwo.setId_question(questionIdFour);
        AnswerThreeToQuestionFourForCourseTwo.setId_question(questionIdFour);
        AnswerFourToQuestionFourForCourseTwo.setId_question(questionIdFour);
        new DatabaseHelper1(context).insertDataToAnswer(AnswerOneToQuestionFourForCourseTwo);
        new DatabaseHelper1(context).insertDataToAnswer(AnswerTwoToQuestionFourForCourseTwo);
        new DatabaseHelper1(context).insertDataToAnswer(AnswerThreeToQuestionFourForCourseTwo);
        new DatabaseHelper1(context).insertDataToAnswer(AnswerFourToQuestionFourForCourseTwo);
        int questionIdFive = 10;
        Data_Answer AnswerOneToQuestionFiveForCourseTwo = new Data_Answer();
        Data_Answer AnswerTwoToQuestionFiveForCourseTwo = new Data_Answer();
        Data_Answer AnswerThreeToQuestionFiveForCourseTwo = new Data_Answer();
        Data_Answer AnswerFourToQuestionFiveForCourseTwo = new Data_Answer();
        AnswerOneToQuestionFiveForCourseTwo.setText("System.out.println(“Hello World”)");
        AnswerTwoToQuestionFiveForCourseTwo.setText("print(“Hello World”)");
        AnswerThreeToQuestionFiveForCourseTwo.setText("document.write(“Hello World”)");
        AnswerFourToQuestionFiveForCourseTwo.setText("response.write(“Hello World”)");
        AnswerOneToQuestionFiveForCourseTwo.setStatus(0);
        AnswerTwoToQuestionFiveForCourseTwo.setStatus(1);
        AnswerThreeToQuestionFiveForCourseTwo.setStatus(0);
        AnswerFourToQuestionFiveForCourseTwo.setStatus(0);
        AnswerOneToQuestionFiveForCourseTwo.setId_question(questionIdFive);
        AnswerTwoToQuestionFiveForCourseTwo.setId_question(questionIdFive);
        AnswerThreeToQuestionFiveForCourseTwo.setId_question(questionIdFive);
        AnswerFourToQuestionFiveForCourseTwo.setId_question(questionIdFive);
        new DatabaseHelper1(context).insertDataToAnswer(AnswerOneToQuestionFiveForCourseTwo);
        new DatabaseHelper1(context).insertDataToAnswer(AnswerTwoToQuestionFiveForCourseTwo);
        new DatabaseHelper1(context).insertDataToAnswer(AnswerThreeToQuestionFiveForCourseTwo);
        new DatabaseHelper1(context).insertDataToAnswer(AnswerFourToQuestionFiveForCourseTwo);
    }
    public void insertAnswersToQuestionsForCourseThree(){
        int questionIdOne = 11;
        Data_Answer AnswerOneToQuestionOneForCourseThree = new Data_Answer();
        Data_Answer AnswerTwoToQuestionOneForCourseThree = new Data_Answer();
        Data_Answer AnswerThreeToQuestionOneForCourseThree = new Data_Answer();
        Data_Answer AnswerFourToQuestionOneForCourseThree = new Data_Answer();
        AnswerOneToQuestionOneForCourseThree.setText("border[round]: 30px;");
        AnswerTwoToQuestionOneForCourseThree.setText("corner-effect: round;");
        AnswerThreeToQuestionOneForCourseThree.setText("border-radius: 30px;");
        AnswerFourToQuestionOneForCourseThree.setText("alpha-effect: round-corner;");
        AnswerOneToQuestionOneForCourseThree.setStatus(0);
        AnswerTwoToQuestionOneForCourseThree.setStatus(0);
        AnswerThreeToQuestionOneForCourseThree.setStatus(1);
        AnswerFourToQuestionOneForCourseThree.setStatus(0);
        AnswerOneToQuestionOneForCourseThree.setId_question(questionIdOne);
        AnswerTwoToQuestionOneForCourseThree.setId_question(questionIdOne);
        AnswerThreeToQuestionOneForCourseThree.setId_question(questionIdOne);
        AnswerFourToQuestionOneForCourseThree.setId_question(questionIdOne);
        new DatabaseHelper1(context).insertDataToAnswer(AnswerOneToQuestionOneForCourseThree);
        new DatabaseHelper1(context).insertDataToAnswer(AnswerTwoToQuestionOneForCourseThree);
        new DatabaseHelper1(context).insertDataToAnswer(AnswerThreeToQuestionOneForCourseThree);
        new DatabaseHelper1(context).insertDataToAnswer(AnswerFourToQuestionOneForCourseThree);
        int questionIdTwo = 12;
        Data_Answer AnswerOneToQuestionTwoForCourseThree = new Data_Answer();
        Data_Answer AnswerTwoToQuestionTwoForCourseThree = new Data_Answer();
        Data_Answer AnswerThreeToQuestionTwoForCourseThree = new Data_Answer();
        Data_Answer AnswerFourToQuestionTwoForCourseThree = new Data_Answer();
        AnswerOneToQuestionTwoForCourseThree.setText("box-shadow: 10px 10px 5px grey;");
        AnswerTwoToQuestionTwoForCourseThree.setText("shadow-right: 10px shadow-bottom: 10px;");
        AnswerThreeToQuestionTwoForCourseThree.setText("shadow-color: grey;");
        AnswerFourToQuestionTwoForCourseThree.setText("alpha-effect[shadow]: 10px 10px 5px grey;");
        AnswerOneToQuestionTwoForCourseThree.setStatus(1);
        AnswerTwoToQuestionTwoForCourseThree.setStatus(0);
        AnswerThreeToQuestionTwoForCourseThree.setStatus(0);
        AnswerFourToQuestionTwoForCourseThree.setStatus(0);
        AnswerOneToQuestionTwoForCourseThree.setId_question(questionIdTwo);
        AnswerTwoToQuestionTwoForCourseThree.setId_question(questionIdTwo);
        AnswerThreeToQuestionTwoForCourseThree.setId_question(questionIdTwo);
        AnswerFourToQuestionTwoForCourseThree.setId_question(questionIdTwo);
        new DatabaseHelper1(context).insertDataToAnswer(AnswerOneToQuestionTwoForCourseThree);
        new DatabaseHelper1(context).insertDataToAnswer(AnswerTwoToQuestionTwoForCourseThree);
        new DatabaseHelper1(context).insertDataToAnswer(AnswerThreeToQuestionTwoForCourseThree);
        new DatabaseHelper1(context).insertDataToAnswer(AnswerFourToQuestionTwoForCourseThree);
        int questionIdThree = 13;
        Data_Answer AnswerOneToQuestionThreeForCourseThree = new Data_Answer();
        Data_Answer AnswerTwoToQuestionThreeForCourseThree = new Data_Answer();
        Data_Answer AnswerThreeToQuestionThreeForCourseThree = new Data_Answer();
        Data_Answer AnswerFourToQuestionThreeForCourseThree = new Data_Answer();
        AnswerOneToQuestionThreeForCourseThree.setText("background-size: 80px 60px;");
        AnswerTwoToQuestionThreeForCourseThree.setText("bg-dimensions: 80px 60px;");
        AnswerThreeToQuestionThreeForCourseThree.setText("background-proportion: 80px 60px;");
        AnswerFourToQuestionThreeForCourseThree.setText("alpha-effect: bg-resize 80px 60px;");
        AnswerOneToQuestionThreeForCourseThree.setStatus(1);
        AnswerTwoToQuestionThreeForCourseThree.setStatus(0);
        AnswerThreeToQuestionThreeForCourseThree.setStatus(0);
        AnswerFourToQuestionThreeForCourseThree.setStatus(0);
        AnswerOneToQuestionThreeForCourseThree.setId_question(questionIdThree);
        AnswerTwoToQuestionThreeForCourseThree.setId_question(questionIdThree);
        AnswerThreeToQuestionThreeForCourseThree.setId_question(questionIdThree);
        AnswerFourToQuestionThreeForCourseThree.setId_question(questionIdThree);
        new DatabaseHelper1(context).insertDataToAnswer(AnswerOneToQuestionThreeForCourseThree);
        new DatabaseHelper1(context).insertDataToAnswer(AnswerTwoToQuestionThreeForCourseThree);
        new DatabaseHelper1(context).insertDataToAnswer(AnswerThreeToQuestionThreeForCourseThree);
        new DatabaseHelper1(context).insertDataToAnswer(AnswerFourToQuestionThreeForCourseThree);
        int questionIdFour = 14;
        Data_Answer AnswerOneToQuestionFourForCourseThree = new Data_Answer();
        Data_Answer AnswerTwoToQuestionFourForCourseThree = new Data_Answer();
        Data_Answer AnswerThreeToQuestionFourForCourseThree = new Data_Answer();
        Data_Answer AnswerFourToQuestionFourForCourseThree = new Data_Answer();
        AnswerOneToQuestionFourForCourseThree.setText("font: shadowed 5px 5px 5px grey;");
        AnswerTwoToQuestionFourForCourseThree.setText("font-shadow: 5px 5px 5px grey;");
        AnswerThreeToQuestionFourForCourseThree.setText("text-shadow: 5px 5px 5px grey;");
        AnswerFourToQuestionFourForCourseThree.setText("shadow: text 5px 5px 5px grey;");
        AnswerOneToQuestionFourForCourseThree.setStatus(0);
        AnswerTwoToQuestionFourForCourseThree.setStatus(0);
        AnswerThreeToQuestionFourForCourseThree.setStatus(1);
        AnswerFourToQuestionFourForCourseThree.setStatus(0);
        AnswerOneToQuestionFourForCourseThree.setId_question(questionIdFour);
        AnswerTwoToQuestionFourForCourseThree.setId_question(questionIdFour);
        AnswerThreeToQuestionFourForCourseThree.setId_question(questionIdFour);
        AnswerFourToQuestionFourForCourseThree.setId_question(questionIdFour);
        new DatabaseHelper1(context).insertDataToAnswer(AnswerOneToQuestionFourForCourseThree);
        new DatabaseHelper1(context).insertDataToAnswer(AnswerTwoToQuestionFourForCourseThree);
        new DatabaseHelper1(context).insertDataToAnswer(AnswerThreeToQuestionFourForCourseThree);
        new DatabaseHelper1(context).insertDataToAnswer(AnswerFourToQuestionFourForCourseThree);
        int questionIdFive = 15;
        Data_Answer AnswerOneToQuestionFiveForCourseThree = new Data_Answer();
        Data_Answer AnswerTwoToQuestionFiveForCourseThree = new Data_Answer();
        Data_Answer AnswerThreeToQuestionFiveForCourseThree = new Data_Answer();
        Data_Answer AnswerFourToQuestionFiveForCourseThree = new Data_Answer();
        AnswerOneToQuestionFiveForCourseThree.setText("object-rotation: 30deg;");
        AnswerTwoToQuestionFiveForCourseThree.setText("transform: rotate(30deg);");
        AnswerThreeToQuestionFiveForCourseThree.setText("rotate-object: 30deg;");
        AnswerFourToQuestionFiveForCourseThree.setText("transform: rotate-30deg-clockwise;");
        AnswerOneToQuestionFiveForCourseThree.setStatus(0);
        AnswerTwoToQuestionFiveForCourseThree.setStatus(1);
        AnswerThreeToQuestionFiveForCourseThree.setStatus(0);
        AnswerFourToQuestionFiveForCourseThree.setStatus(0);
        AnswerOneToQuestionFiveForCourseThree.setId_question(questionIdFive);
        AnswerTwoToQuestionFiveForCourseThree.setId_question(questionIdFive);
        AnswerThreeToQuestionFiveForCourseThree.setId_question(questionIdFive);
        AnswerFourToQuestionFiveForCourseThree.setId_question(questionIdFive);
        new DatabaseHelper1(context).insertDataToAnswer(AnswerOneToQuestionFiveForCourseThree);
        new DatabaseHelper1(context).insertDataToAnswer(AnswerTwoToQuestionFiveForCourseThree);
        new DatabaseHelper1(context).insertDataToAnswer(AnswerThreeToQuestionFiveForCourseThree);
        new DatabaseHelper1(context).insertDataToAnswer(AnswerFourToQuestionFiveForCourseThree);
    }
    public void insertAnswersToQuestionsForCourseFour(){
        int questionIdOne = 16;
        Data_Answer AnswerOneToQuestionOneForCourseFour = new Data_Answer();
        Data_Answer AnswerTwoToQuestionOneForCourseFour = new Data_Answer();
        Data_Answer AnswerThreeToQuestionOneForCourseFour = new Data_Answer();
        Data_Answer AnswerFourToQuestionOneForCourseFour = new Data_Answer();
        AnswerOneToQuestionOneForCourseFour.setText("SELECT CURTIME();");
        AnswerTwoToQuestionOneForCourseFour.setText("SELECT CURDATE();");
        AnswerThreeToQuestionOneForCourseFour.setText("SELECT CURRENT_TIME();");
        AnswerFourToQuestionOneForCourseFour.setText("All of above");
        AnswerOneToQuestionOneForCourseFour.setStatus(0);
        AnswerTwoToQuestionOneForCourseFour.setStatus(0);
        AnswerThreeToQuestionOneForCourseFour.setStatus(0);
        AnswerFourToQuestionOneForCourseFour.setStatus(1);
        AnswerOneToQuestionOneForCourseFour.setId_question(questionIdOne);
        AnswerTwoToQuestionOneForCourseFour.setId_question(questionIdOne);
        AnswerThreeToQuestionOneForCourseFour.setId_question(questionIdOne);
        AnswerFourToQuestionOneForCourseFour.setId_question(questionIdOne);
        new DatabaseHelper1(context).insertDataToAnswer(AnswerOneToQuestionOneForCourseFour);
        new DatabaseHelper1(context).insertDataToAnswer(AnswerTwoToQuestionOneForCourseFour);
        new DatabaseHelper1(context).insertDataToAnswer(AnswerThreeToQuestionOneForCourseFour);
        new DatabaseHelper1(context).insertDataToAnswer(AnswerFourToQuestionOneForCourseFour);
        int questionIdTwo = 17;
        Data_Answer AnswerOneToQuestionTwoForCourseFour = new Data_Answer();
        Data_Answer AnswerTwoToQuestionTwoForCourseFour = new Data_Answer();
        Data_Answer AnswerThreeToQuestionTwoForCourseFour = new Data_Answer();
        Data_Answer AnswerFourToQuestionTwoForCourseFour = new Data_Answer();
        AnswerOneToQuestionTwoForCourseFour.setText("Table");
        AnswerTwoToQuestionTwoForCourseFour.setText("Column");
        AnswerThreeToQuestionTwoForCourseFour.setText("Database");
        AnswerFourToQuestionTwoForCourseFour.setText("All of above");
        AnswerOneToQuestionTwoForCourseFour.setStatus(1);
        AnswerTwoToQuestionTwoForCourseFour.setStatus(0);
        AnswerThreeToQuestionTwoForCourseFour.setStatus(0);
        AnswerFourToQuestionTwoForCourseFour.setStatus(0);
        AnswerOneToQuestionTwoForCourseFour.setId_question(questionIdTwo);
        AnswerTwoToQuestionTwoForCourseFour.setId_question(questionIdTwo);
        AnswerThreeToQuestionTwoForCourseFour.setId_question(questionIdTwo);
        AnswerFourToQuestionTwoForCourseFour.setId_question(questionIdTwo);
        new DatabaseHelper1(context).insertDataToAnswer(AnswerOneToQuestionTwoForCourseFour);
        new DatabaseHelper1(context).insertDataToAnswer(AnswerTwoToQuestionTwoForCourseFour);
        new DatabaseHelper1(context).insertDataToAnswer(AnswerThreeToQuestionTwoForCourseFour);
        new DatabaseHelper1(context).insertDataToAnswer(AnswerFourToQuestionTwoForCourseFour);
        int questionIdThree = 18;
        Data_Answer AnswerOneToQuestionThreeForCourseFour = new Data_Answer();
        Data_Answer AnswerTwoToQuestionThreeForCourseFour = new Data_Answer();
        Data_Answer AnswerThreeToQuestionThreeForCourseFour = new Data_Answer();
        Data_Answer AnswerFourToQuestionThreeForCourseFour = new Data_Answer();
        AnswerOneToQuestionThreeForCourseFour.setText("AND");
        AnswerTwoToQuestionThreeForCourseFour.setText("WHERE");
        AnswerThreeToQuestionThreeForCourseFour.setText("HAVING");
        AnswerFourToQuestionThreeForCourseFour.setText("FROM");
        AnswerOneToQuestionThreeForCourseFour.setStatus(0);
        AnswerTwoToQuestionThreeForCourseFour.setStatus(1);
        AnswerThreeToQuestionThreeForCourseFour.setStatus(0);
        AnswerFourToQuestionThreeForCourseFour.setStatus(0);
        AnswerOneToQuestionThreeForCourseFour.setId_question(questionIdThree);
        AnswerTwoToQuestionThreeForCourseFour.setId_question(questionIdThree);
        AnswerThreeToQuestionThreeForCourseFour.setId_question(questionIdThree);
        AnswerFourToQuestionThreeForCourseFour.setId_question(questionIdThree);
        new DatabaseHelper1(context).insertDataToAnswer(AnswerOneToQuestionThreeForCourseFour);
        new DatabaseHelper1(context).insertDataToAnswer(AnswerTwoToQuestionThreeForCourseFour);
        new DatabaseHelper1(context).insertDataToAnswer(AnswerThreeToQuestionThreeForCourseFour);
        new DatabaseHelper1(context).insertDataToAnswer(AnswerFourToQuestionThreeForCourseFour);
        int questionIdFour = 19;
        Data_Answer AnswerOneToQuestionFourForCourseFour = new Data_Answer();
        Data_Answer AnswerTwoToQuestionFourForCourseFour = new Data_Answer();
        Data_Answer AnswerThreeToQuestionFourForCourseFour = new Data_Answer();
        Data_Answer AnswerFourToQuestionFourForCourseFour = new Data_Answer();
        AnswerOneToQuestionFourForCourseFour.setText("64");
        AnswerTwoToQuestionFourForCourseFour.setText("55");
        AnswerThreeToQuestionFourForCourseFour.setText("72");
        AnswerFourToQuestionFourForCourseFour.setText("40");
        AnswerOneToQuestionFourForCourseFour.setStatus(0);
        AnswerTwoToQuestionFourForCourseFour.setStatus(0);
        AnswerThreeToQuestionFourForCourseFour.setStatus(0);
        AnswerFourToQuestionFourForCourseFour.setStatus(1);
        AnswerOneToQuestionFourForCourseFour.setId_question(questionIdFour);
        AnswerTwoToQuestionFourForCourseFour.setId_question(questionIdFour);
        AnswerThreeToQuestionFourForCourseFour.setId_question(questionIdFour);
        AnswerFourToQuestionFourForCourseFour.setId_question(questionIdFour);
        new DatabaseHelper1(context).insertDataToAnswer(AnswerOneToQuestionFourForCourseFour);
        new DatabaseHelper1(context).insertDataToAnswer(AnswerTwoToQuestionFourForCourseFour);
        new DatabaseHelper1(context).insertDataToAnswer(AnswerThreeToQuestionFourForCourseFour);
        new DatabaseHelper1(context).insertDataToAnswer(AnswerFourToQuestionFourForCourseFour);
        int questionIdFive = 20;
        Data_Answer AnswerOneToQuestionFiveForCourseFour = new Data_Answer();
        Data_Answer AnswerTwoToQuestionFiveForCourseFour = new Data_Answer();
        Data_Answer AnswerThreeToQuestionFiveForCourseFour = new Data_Answer();
        Data_Answer AnswerFourToQuestionFiveForCourseFour = new Data_Answer();
        AnswerOneToQuestionFiveForCourseFour.setText("SELECT * FROM students");
        AnswerTwoToQuestionFiveForCourseFour.setText("SELECT * FROM ` students `;");
        AnswerThreeToQuestionFiveForCourseFour.setText("SELECT * FROM \" students \";");
        AnswerFourToQuestionFiveForCourseFour.setText("SELECT * FROM ' students ';");
        AnswerOneToQuestionFiveForCourseFour.setStatus(1);
        AnswerTwoToQuestionFiveForCourseFour.setStatus(0);
        AnswerThreeToQuestionFiveForCourseFour.setStatus(0);
        AnswerFourToQuestionFiveForCourseFour.setStatus(0);
        AnswerOneToQuestionFiveForCourseFour.setId_question(questionIdFive);
        AnswerTwoToQuestionFiveForCourseFour.setId_question(questionIdFive);
        AnswerThreeToQuestionFiveForCourseFour.setId_question(questionIdFive);
        AnswerFourToQuestionFiveForCourseFour.setId_question(questionIdFive);
        new DatabaseHelper1(context).insertDataToAnswer(AnswerOneToQuestionFiveForCourseFour);
        new DatabaseHelper1(context).insertDataToAnswer(AnswerTwoToQuestionFiveForCourseFour);
        new DatabaseHelper1(context).insertDataToAnswer(AnswerThreeToQuestionFiveForCourseFour);
        new DatabaseHelper1(context).insertDataToAnswer(AnswerFourToQuestionFiveForCourseFour);
    }
    public void insertAnswersToQuestionsForCourseFive(){
        int questionIdOne = new DatabaseHelper1(context).getLastIdOfQuestion() + 1;
        Data_Answer AnswersToQuestionOneForCourseFive = new Data_Answer();
        AnswersToQuestionOneForCourseFive.setText("RR1.getText().toString()");
        AnswersToQuestionOneForCourseFive.setText("RR2.getText().toString()");
        AnswersToQuestionOneForCourseFive.setText("RR3.getText().toString()");
        AnswersToQuestionOneForCourseFive.setText("RR4.getText().toString())");
        AnswersToQuestionOneForCourseFive.setId_question(questionIdOne);
        AnswersToQuestionOneForCourseFive.setId_question(questionIdOne);
        AnswersToQuestionOneForCourseFive.setId_question(questionIdOne);
        AnswersToQuestionOneForCourseFive.setId_question(questionIdOne);
        new DatabaseHelper1(context).insertDataToAnswer(AnswersToQuestionOneForCourseFive);
        new DatabaseHelper1(context).insertDataToAnswer(AnswersToQuestionOneForCourseFive);
        new DatabaseHelper1(context).insertDataToAnswer(AnswersToQuestionOneForCourseFive);
        new DatabaseHelper1(context).insertDataToAnswer(AnswersToQuestionOneForCourseFive);
        int questionIdTwo = new DatabaseHelper1(context).getLastIdOfQuestion() + 1;
        Data_Answer AnswersToQuestionTwoForCourseFive = new Data_Answer();
        AnswersToQuestionTwoForCourseFive.setText("RR1.getText().toString()");
        AnswersToQuestionTwoForCourseFive.setText("RR2.getText().toString()");
        AnswersToQuestionTwoForCourseFive.setText("RR3.getText().toString()");
        AnswersToQuestionTwoForCourseFive.setText("RR4.getText().toString())");
        AnswersToQuestionTwoForCourseFive.setId_question(questionIdTwo);
        AnswersToQuestionTwoForCourseFive.setId_question(questionIdTwo);
        AnswersToQuestionTwoForCourseFive.setId_question(questionIdTwo);
        AnswersToQuestionTwoForCourseFive.setId_question(questionIdTwo);
        new DatabaseHelper1(context).insertDataToAnswer(AnswersToQuestionTwoForCourseFive);
        new DatabaseHelper1(context).insertDataToAnswer(AnswersToQuestionTwoForCourseFive);
        new DatabaseHelper1(context).insertDataToAnswer(AnswersToQuestionTwoForCourseFive);
        new DatabaseHelper1(context).insertDataToAnswer(AnswersToQuestionTwoForCourseFive);
        int questionIdThree = new DatabaseHelper1(context).getLastIdOfQuestion() + 1;
        Data_Answer AnswersToQuestionThreeForCourseFive = new Data_Answer();
        AnswersToQuestionThreeForCourseFive.setText("RR1.getText().toString()");
        AnswersToQuestionThreeForCourseFive.setText("RR2.getText().toString()");
        AnswersToQuestionThreeForCourseFive.setText("RR3.getText().toString()");
        AnswersToQuestionThreeForCourseFive.setText("RR4.getText().toString())");
        AnswersToQuestionThreeForCourseFive.setId_question(questionIdThree);
        AnswersToQuestionThreeForCourseFive.setId_question(questionIdThree);
        AnswersToQuestionThreeForCourseFive.setId_question(questionIdThree);
        AnswersToQuestionThreeForCourseFive.setId_question(questionIdThree);
        new DatabaseHelper1(context).insertDataToAnswer(AnswersToQuestionThreeForCourseFive);
        new DatabaseHelper1(context).insertDataToAnswer(AnswersToQuestionThreeForCourseFive);
        new DatabaseHelper1(context).insertDataToAnswer(AnswersToQuestionThreeForCourseFive);
        new DatabaseHelper1(context).insertDataToAnswer(AnswersToQuestionThreeForCourseFive);
        int questionIdFour = new DatabaseHelper1(context).getLastIdOfQuestion() + 1;
        Data_Answer AnswersToQuestionFourForCourseFive = new Data_Answer();
        AnswersToQuestionFourForCourseFive.setText("RR1.getText().toString()");
        AnswersToQuestionFourForCourseFive.setText("RR2.getText().toString()");
        AnswersToQuestionFourForCourseFive.setText("RR3.getText().toString()");
        AnswersToQuestionFourForCourseFive.setText("RR4.getText().toString())");
        AnswersToQuestionFourForCourseFive.setId_question(questionIdFour);
        AnswersToQuestionFourForCourseFive.setId_question(questionIdFour);
        AnswersToQuestionFourForCourseFive.setId_question(questionIdFour);
        AnswersToQuestionFourForCourseFive.setId_question(questionIdFour);
        new DatabaseHelper1(context).insertDataToAnswer(AnswersToQuestionFourForCourseFive);
        new DatabaseHelper1(context).insertDataToAnswer(AnswersToQuestionFourForCourseFive);
        new DatabaseHelper1(context).insertDataToAnswer(AnswersToQuestionFourForCourseFive);
        new DatabaseHelper1(context).insertDataToAnswer(AnswersToQuestionFourForCourseFive);
        int questionIdFive = new DatabaseHelper1(context).getLastIdOfQuestion() + 1;
        Data_Answer AnswersToQuestionFiveForCourseFive = new Data_Answer();
        AnswersToQuestionFiveForCourseFive.setText("RR1.getText().toString()");
        AnswersToQuestionFiveForCourseFive.setText("RR2.getText().toString()");
        AnswersToQuestionFiveForCourseFive.setText("RR3.getText().toString()");
        AnswersToQuestionFiveForCourseFive.setText("RR4.getText().toString())");
        AnswersToQuestionFiveForCourseFive.setId_question(questionIdFive);
        AnswersToQuestionFiveForCourseFive.setId_question(questionIdFive);
        AnswersToQuestionFiveForCourseFive.setId_question(questionIdFive);
        AnswersToQuestionFiveForCourseFive.setId_question(questionIdFive);
        new DatabaseHelper1(context).insertDataToAnswer(AnswersToQuestionFiveForCourseFive);
        new DatabaseHelper1(context).insertDataToAnswer(AnswersToQuestionFiveForCourseFive);
        new DatabaseHelper1(context).insertDataToAnswer(AnswersToQuestionFiveForCourseFive);
        new DatabaseHelper1(context).insertDataToAnswer(AnswersToQuestionFiveForCourseFive);
    }

}
